// <auto-generated />
using System;
using CountwareTraffic.Workers.Sms.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CountwareTraffic.Workers.Sms.Data.Migrations
{
    [DbContext(typeof(SmsDbContext))]
    [Migration("20220211103311_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CountwareTraffic.Workers.Sms.Data.SmsLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOtp")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumbers")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("Response")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SmsBody")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("UserIds")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<int>("_smsTypeId")
                        .HasColumnType("int")
                        .HasColumnName("SmsTypeId");

                    b.HasKey("Id");

                    b.HasIndex("_smsTypeId");

                    b.ToTable("SmsLogs", "app");
                });

            modelBuilder.Entity("CountwareTraffic.Workers.Sms.Data.SmsType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SmsTypes", "app");
                });

            modelBuilder.Entity("CountwareTraffic.Workers.Sms.Data.SmsLog", b =>
                {
                    b.HasOne("CountwareTraffic.Workers.Sms.Data.SmsType", "SmsType")
                        .WithMany()
                        .HasForeignKey("_smsTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmsType");
                });
#pragma warning restore 612, 618
        }
    }
}
