// <auto-generated />
using System;
using CountwareTraffic.WorkerServices.Email.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CountwareTraffic.WorkerServices.Email.Data.Migrations
{
    [DbContext(typeof(EmailDbContext))]
    [Migration("20220211103033_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CountwareTraffic.WorkerServices.Email.Data.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailBody")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("EmailSubject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EmailTo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("bit");

                    b.Property<string>("Response")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UserIds")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("_emailTypeId")
                        .HasColumnType("int")
                        .HasColumnName("EmailTypeId");

                    b.HasKey("Id");

                    b.HasIndex("_emailTypeId");

                    b.ToTable("EmailLogs", "app");
                });

            modelBuilder.Entity("CountwareTraffic.WorkerServices.Email.Data.EmailType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EmailTypes", "app");
                });

            modelBuilder.Entity("CountwareTraffic.WorkerServices.Email.Data.EmailLog", b =>
                {
                    b.HasOne("CountwareTraffic.WorkerServices.Email.Data.EmailType", "EmailType")
                        .WithMany()
                        .HasForeignKey("_emailTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailType");
                });
#pragma warning restore 612, 618
        }
    }
}
